import {readFile} from "node:fs/promises";
import assert from "node:assert/strict";
import vm from "node:vm";
const content=await readFile("app.js","utf8");
const storage=await readFile("state-storage.js","utf8");
const ctx=vm.createContext({URL,document:{addEventListener(){}}});
vm.runInContext(storage,ctx,{filename:"state-storage.js"});
vm.runInContext(content,ctx,{filename:"app.js"});
function invoke(statement){return vm.runInContext(statement,ctx)}
const example="https://dbv.turnier.de/tournament/E24DC6EE-152A-454D-B00C-E625B751D7D5";
assert.equal(invoke('parseDbvTournamentLink('+JSON.stringify(example)+').id'),"E24DC6EE-152A-454D-B00C-E625B751D7D5");
assert.equal(invoke('parseDbvTournamentLink('+JSON.stringify(example+"?foo=bar")+').url'),example);
assert.equal(invoke('parseDbvTournamentLink("https://evil.example/tournament/E24DC6EE-152A-454D-B00C-E625B751D7D5")'),null);
assert.equal(invoke('parseDbvTournamentLink("https://dbv.turnier.de/tournament/garbage")'),null);
assert.equal(invoke('parseDbvTournamentLink("javascript:alert(1)")'),null);
const normalized=invoke('normalizeBookmark({url:'+JSON.stringify(example)+',name:"",playerId:"05-070879"})');
assert.equal(normalized.id,"E24DC6EE-152A-454D-B00C-E625B751D7D5");
assert.equal(normalized.name,"DBV-Turnier E24DC6EE");
assert.equal(normalized.playerId,"05-070879");
assert.equal(normalized.startDate,"");
assert.equal(normalized.endDate,"");
const full=invoke('normalizeBookmark({url:'+JSON.stringify(example)+',name:"Mein Turnier",playerId:"all",startDate:"2026-11-10",endDate:"2026-11-11"})');
assert.equal(full.name,"Mein Turnier");
assert.equal(full.startDate,"2026-11-10");
assert.equal(full.endDate,"2026-11-11");
assert.equal(invoke('state.officialLinks.length'),0,"New devices should not get unsolicited tournament records");
assert.ok(storage.includes('localStorage.setItem(STORE'));
assert.ok(storage.includes('saved.officialLinks'));
assert.ok(content.includes('state.officialLinks.unshift(bookmark)'));
assert.ok(content.includes('data-edit-id'));
assert.ok(content.includes('data-remove-id'));
assert.ok(!content.includes('fetch('),"Tournament bookmarks must not scrape official pages");
const html=await readFile("index.html","utf8");
assert.ok(html.includes('id="tournament-dialog-heading"'));
assert.ok(html.includes('id="tournament-save"'));
console.log("DBV bookmark tests passed: IDs, URL safety, URL-only entry, optional metadata, editing, persistence.");
