import {readFile} from "node:fs/promises";
import assert from "node:assert/strict";
import {summarizeTrophies,TROPHY_PLACES} from "../scripts/trophy-stats.mjs";
const {results}=JSON.parse(await readFile("data/history.json","utf8"));
const philipp=results.filter(r=>r.playerId==="05-070879");
const charlotte=results.filter(r=>r.playerName==="Charlotte Metzger");
const p=summarizeTrophies(philipp);
assert.deepEqual(TROPHY_PLACES,[1,2,3,4]);
assert.deepEqual(p.counts,{1:2,2:1,3:2,4:2});
assert.equal(p.total,7);
assert.equal(p.results.filter(r=>r.event.includes("Bezirksmeisterschaft")&&r.discipline==="Einzel"&&r.place===1).length,1);
assert.equal(p.results.filter(r=>r.confirmation==="family-confirmed").length,2);
assert.ok(p.results.some(r=>r.id.includes("gaertringen")));
const c=summarizeTrophies(charlotte);
assert.deepEqual(c.counts,{1:0,2:0,3:0,4:0});
assert.equal(c.total,0,"Charlotte's documented 5th place must remain in history, not the trophy cabinet");
const family=summarizeTrophies(results);
assert.equal(family.total,7);
assert.equal(family.results.filter(r=>r.place===4).length,2);
assert.deepEqual(summarizeTrophies(philipp.filter(r=>r.date.startsWith("2025"))).counts,{1:0,2:0,3:1,4:1});
assert.deepEqual(summarizeTrophies([...philipp,philipp[0]]).counts,p.counts,"Duplicate sources must not add extra trophies");
assert.deepEqual(summarizeTrophies([...philipp,{id:"made-up",place:1,verified:false}]).counts,p.counts,"Unverified results must not grant trophies");
assert.deepEqual(summarizeTrophies(null).counts,{1:0,2:0,3:0,4:0});
const html=await readFile("index.html","utf8");
assert.ok(html.includes('id="trophy-shelf"')&&html.includes('id="trophy-awards"'));
assert.ok(html.includes('type="module" src="./history.js"'),"Browser must load ESM imports");
const ui=await readFile("history.js","utf8");
assert.ok(ui.includes("summarizeTrophies(chosen)")&&ui.includes("renderTrophies(chosen)"));
assert.ok(ui.includes("trophyPlace")&&ui.includes("Turnierbericht ansehen"));
const css=await readFile("styles.css","utf8");
assert.ok(css.includes(".trophy-slot")&&css.includes(".trophy-award"));
const sw=await readFile("sw.js","utf8");
assert.ok(sw.includes("./scripts/trophy-stats.mjs"));
console.log("Trophy cabinet passed: Philipp 2×1st, 1×2nd, 2×3rd, 2×4th; Charlotte 5th excluded.");
