import {readFile,access} from "node:fs/promises";
import assert from "node:assert/strict";
for(const file of ["index.html","styles.css","app.js","sw.js","manifest.webmanifest","assets/spvgg-schmetterlinge.svg","data/live.json","scripts/sync-feed.mjs"])await access(file);
const data=JSON.parse(await readFile("data/live.json","utf8"));
assert.equal(data.schemaVersion,1);
assert.ok(["unconfigured","connected"].includes(data.connection));
assert.ok(Array.isArray(data.matches)&&Array.isArray(data.tournaments));
if(data.connection==="unconfigured")assert.equal(data.matches.length,0,"Do not ship invented live matches");
const page=await readFile("index.html","utf8");
for(const id of ["match-list","player-pills","profile-list","player-dialog","demo-toggle","next-match"])assert.ok(page.includes('id="'+id+'"'));
assert.ok(page.includes("assets/spvgg-schmetterlinge.svg"),"Missing approved Schmetterlinge emblem");
const {createHash}=await import("node:crypto");
const crest=await readFile("assets/spvgg-schmetterlinge.svg","utf8");
const embedded=crest.match(/data:image\/webp;base64,([^"]+)/)?.[1];
assert.ok(embedded,"Original Schmetterlinge crest must be embedded");
assert.equal(createHash("sha256").update(Buffer.from(embedded,"base64")).digest("hex"),"8aced9ebd1eb23035fd59a18d2ddb332ac6c754da11328011f9e3613a32d1fb3","Use only the approved logo supplied on 9 October 2026");
console.log("Starter snapshot, original crest and app structure valid.");
