import {readFile,access} from "node:fs/promises";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
for(const path of ["index.html","styles.css","state-storage.js","app.js","history.js","sw.js","manifest.webmanifest","assets/spvgg-schmetterlinge.svg","data/history.json","scripts/trophy-stats.mjs"])await access(path);
const html=await readFile("index.html","utf8");
for(const id of ["focused-profile","profile-list","friend-list","friend-dialog","add-friend","view-einstellungen","player-dialog","tournament-dialog","tournament-form","add-tournament","official-tournament-list","view-historie","trophy-shelf","trophy-awards"])assert.ok(html.includes('id="'+id+'"'),"Missing "+id);
for(const id of ["next-match","feed-badge","demo-toggle","match-list","notify"])assert.ok(!html.includes('id="'+id+'"'),"Obsolete live UI: "+id);
assert.ok(html.includes('name="url" type="url" required'));
assert.ok(html.includes('name="startDate" type="date"'));
assert.ok(html.includes('name="endDate" type="date"'));
assert.ok(html.includes("assets/spvgg-schmetterlinge.svg"));
const css=await readFile("styles.css","utf8");
assert.ok(css.includes("clip-path:none!important"),"Header logo must not be clipped into a circular badge");
assert.ok(css.includes("mask:none!important;-webkit-mask:none!important"),"Approved butterfly crest must not be faded by a radial mask");
assert.ok(css.includes("width:94px!important;height:94px!important"),"Mobile logo should be large enough to recognize");
const svg=await readFile("assets/spvgg-schmetterlinge.svg","utf8");
const embedded=svg.match(/data:image\/webp;base64,([^"]+)/)?.[1];
assert.ok(embedded,"Approved logo missing");
assert.equal(createHash("sha256").update(Buffer.from(embedded,"base64")).digest("hex"),"8aced9ebd1eb23035fd59a18d2ddb332ac6c754da11328011f9e3613a32d1fb3");
assert.ok(!html.includes('id="player-pills"'),"No family-wide player switch on home");
console.log("Focused user settings, friends, tournament bookmarks and approved crest valid.");
